name: Run tests

on: [push]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [5.6.4, 5.1.*]
          #- [5.6.4, 5.2.*]
          #- [5.6.4, 5.3.*]
          #- [5.6.4, 5.4.*]
          #- [7.0, 5.5.*]
          #- [7.1.3, 5.6.*]
          #- [7.1.3, 5.7.*]
          #- [7.1.3, 5.8.*]
          #- [7.2.0, 6.0.*]
          #- [7.2.0, 6.2.*]
          #- [7.2.0, 6.4.*]
          #- [7.2.5, 7.0.*]
          #- [7.2.5, 7.3.*]
          #- [7.2.5, 7.6.*]
          #- [7.2.5, 7.12.*]
          #- [7.3, 8.*]
          #- [8.0, 9.*]
          #- [8.1, 10.*]

    name: P${{ matrix.version.0 }} - I${{ matrix.version.1 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version.0 }}
          extensions: mbstring, fileinfo
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.env-setup.outputs.dir }}
          key: php-${{ matrix.version.0 }}-illuminate-${{ matrix.version.1 }}-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.version.0 }}-illuminate-${{ matrix.version.1 }}-composer-

      - name: Install dependencies
        run: |
          composer require "illuminate/support:${{ matrix.version.1 }}" --no-interaction --no-update
          composer update --prefer-source --no-interaction --no-suggest
      - name: Execute tests
        run: vendor/bin/phpunit --debug -c phpunit.xml

