name: Run tests

on: [push]

jobs:
    php-tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [5.6.4, 7.0, 7.1, 7.2, 7.3, 8.0, 8.1]
                illuminate: [5.1.*, 5.2.*, 5.3.*, 5.4.*, 5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*, 9.*, 10.*]

        name: P${{ matrix.php }} - I${{ matrix.illuminate }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring, fileinfo
                  coverage: none
                  tools: composer:v2

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: php-${{ matrix.php }}-illuminate-${{ matrix.illuminate }}-${{ hashFiles('**/composer.json') }}
                  restore-keys: php-${{ matrix.php }}-illuminate-${{ matrix.illuminate }}-composer-

            -  name: Install dependencies
               run: |
                    composer require "illuminate/support:${{ matrix.illuminate }}" --no-interaction --no-update
                    composer update --prefer-source --no-interaction --no-suggest
            - name: Execute tests
              run: vendor/bin/phpunit --debug -c phpunit.xml

